/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userinterface.customer;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Enterprise.BeautyEnterprise;
import Business.Enterprise.Enterprise;
import Business.Order.Item;
import Business.Order.Order;
import Business.Organization.CSROrganization;
import Business.Organization.Organization;
import Business.Organization.customerOrganization;
import Business.Product.Product;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.OrderReminderRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wuxinyang
 */
public class OrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrderJPanel
     */
    
     private JPanel userProcessContainer;
     private BeautyEnterprise benterprise;
     private customerOrganization corganization;
    // private Enterprise enterprise;
     private EcoSystem business;
     private UserAccount account;
    OrderJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount account, Organization organization, EcoSystem business) {
         initComponents();
        this.userProcessContainer= userProcessContainer;
        this.benterprise = (BeautyEnterprise)enterprise;
        this.corganization=(customerOrganization)organization;
       // this.enterprise=enterprise;
        this.business=business;
        this.account= account;
         customer.setText(account.getCustomer().getLname()+" "+ account.getCustomer().getFname());
         populateOrderTable();
         populateDelete();
         populateReminder();
    }
     
    
    
    
    public void populateOrderTable(){
        DefaultTableModel model = (DefaultTableModel) orderTbl.getModel();
        
        model.setRowCount(0);
         
        
       
      
            for (Order o : account.getCustomer().getOrderDir().getOrderList()){{
                
            Object[] row = new Object[5];
            row[0] = o;
          //  row[1] = customer.getFname() + " " + customer.getLname();
            row[1] = o.getDateCreated();             
            row[2] = o.getStatues();
          
            model.addRow(row);
            
            }
       } 
    
       }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        orderTbl = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();
        detailBtn = new javax.swing.JButton();
        productBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        customer = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        requestBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        reminderTbl = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        orderStatusCombo = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        deleteCombo = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        reminderCombo = new javax.swing.JComboBox<>();

        orderTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "OrderId", "Date Created", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orderTbl);

        itemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Quantity", "Price", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(itemTable);

        detailBtn.setText("view order detail");
        detailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailBtnActionPerformed(evt);
            }
        });

        productBtn.setText("view Product detail");
        productBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Order for: ");

        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jButton2.setText("Reminder");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        requestBtn.setText("Request Delete");
        requestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestBtnActionPerformed(evt);
            }
        });

        reminderTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "OrderId", "Date Reminder", "Reminder Message", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(reminderTbl);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "OrderId", "Date Request", "Request Message", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("view all");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        orderStatusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pending", "shipped" }));

        jButton4.setText("search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("view all");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        deleteCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Waiting", "Canceled" }));

        jButton6.setText("view all");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("search");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        reminderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "processing", "processed" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(detailBtn)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(productBtn)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(customer, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(requestBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(orderStatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(reminderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(deleteCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(back)
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customer, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(detailBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(productBtn)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(orderStatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deleteCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addGap(65, 65, 65)
                        .addComponent(reminderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(back)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(requestBtn)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void detailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailBtnActionPerformed
        // TODO add your handling code here:
        int selectedrow = orderTbl.getSelectedRow();
        if(selectedrow<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Order order = (Order)orderTbl.getValueAt(selectedrow, 0);
        int id = order.getOrderId();
        DefaultTableModel model = (DefaultTableModel) itemTable.getModel();
        model.setRowCount(0);
        for(Customer customer : benterprise.getCustomerDir().getCustomerList()){
            for(Order o : customer.getOrderDir().getOrderList()){
                if(o.getOrderId()==id){
                    for(Item item : o.getOrderItemList()){
                        Object[] row = new Object[4];
                        row[0] = item.getProduct();
                        row[1] = item.getQuatity();
                        row[2] = item.getProduct().getSalesPrice();            
                        row[3] = item.getQuatity() * item.getProduct().getSalesPrice();
                        model.addRow(row);
                    }

                }

            }
        }

    }//GEN-LAST:event_detailBtnActionPerformed

    private void productBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productBtnActionPerformed
        // TODO add your handling code here:
          int row = itemTable.getSelectedRow();
        if(row<0) {
             JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Product p = (Product)itemTable.getValueAt(row, 0);
         
        
        
        itemDetailJPanel pd = new itemDetailJPanel(userProcessContainer,benterprise,p);
        userProcessContainer.add("itemDetailJPanel", pd);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
        
    }//GEN-LAST:event_productBtnActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
        
    }//GEN-LAST:event_backActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = reminderTbl.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

       

        OrderReminderRequest request = (OrderReminderRequest)reminderTbl.getValueAt(selectedRow, 0);
       if( reminderTbl.getValueAt(selectedRow, 2).equals("Please Processing")   ){
           JOptionPane.showMessageDialog(null, "Already reminder!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
       }
        
        
        ((OrderReminderRequest)request).setMessage("Please Processing");

        populateReminder();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void requestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else if( jTable1.getValueAt(selectedRow, 2).equals("Please Cancel")   ){
           JOptionPane.showMessageDialog(null, "Already request!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
       }
        else if( jTable1.getValueAt(selectedRow, 3).equals("Canceled")   ){
           JOptionPane.showMessageDialog(null, "Already canceled!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
       }

        //   Order order = (Order)orderTbl.getValueAt(selectedRow, 0);

        OrderReminderRequest request = (OrderReminderRequest)jTable1.getValueAt(selectedRow, 0);
        
        
        //    request.setOrderId(order.getOrderId());
        ((OrderReminderRequest)request).setDeleteMessage("Please Cancel");
       
        ((OrderReminderRequest)request).setDeleteStatus("Waiting");
        Organization org = null;
        for (Organization organization : benterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof CSROrganization){
                org = organization;
                break;

            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
           

            populateDelete();

        }

    }//GEN-LAST:event_requestBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if(orderStatusCombo.getSelectedItem().equals("pending")){
             DefaultTableModel model = (DefaultTableModel) orderTbl.getModel();
        
        model.setRowCount(0);
         
        
       
       for(Customer customer : benterprise.getCustomerDir().getCustomerList()){
            for (Order o : account.getCustomer().getOrderDir().getOrderList()){{
                  if(o.getStatues().equals("pending")){
            Object[] row = new Object[5];
            row[0] = o;
          //  row[1] = customer.getFname() + " " + customer.getLname();
            row[1] = o.getDateCreated();             
            row[2] = o.getStatues();
          
            model.addRow(row);
            
            }
            }
       } 
    }
         
        
       
      
        }else if(orderStatusCombo.getSelectedItem().equals("shipped")){
            DefaultTableModel model = (DefaultTableModel) orderTbl.getModel();
        
        model.setRowCount(0);
         
        
       
       for(Customer customer : benterprise.getCustomerDir().getCustomerList()){
            for (Order o : account.getCustomer().getOrderDir().getOrderList()){{
                  if(o.getStatues().equals("shipped")){
            Object[] row = new Object[5];
            row[0] = o;
          //  row[1] = customer.getFname() + " " + customer.getLname();
            row[1] = o.getDateCreated();             
            row[2] = o.getStatues();
          
            model.addRow(row);
            
            }
            }
       } 
    }
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         if(deleteCombo.getSelectedItem().equals("Waiting")){
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);  
       for(WorkRequest request : account.getWorkQueue().getWorkRequestList()){
          
           if(((OrderReminderRequest)request).getDeleteStatus().equals("Waiting")){
            Object[] row = new Object[4];
            row[0] = (OrderReminderRequest)request;
            row[1] = ((OrderReminderRequest)request).getRequestCreated();
            row[2] = ((OrderReminderRequest)request).getDeleteMessage();
            row[3] = ((OrderReminderRequest)request).getDeleteStatus();
            model.addRow(row);  
    }
       }
        }else if(deleteCombo.getSelectedItem().equals("Canceled")){
              DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
              model.setRowCount(0);  
       for(WorkRequest request : account.getWorkQueue().getWorkRequestList()){
          
           if(((OrderReminderRequest)request).getDeleteStatus().equals("Canceled")){
            Object[] row = new Object[4];
            row[0] = (OrderReminderRequest)request;
            row[1] = ((OrderReminderRequest)request).getRequestCreated();
            row[2] = ((OrderReminderRequest)request).getDeleteMessage();
            row[3] = ((OrderReminderRequest)request).getDeleteStatus();
            model.addRow(row);  
    }
       }
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(reminderCombo.getSelectedItem().equals("processing")){
        DefaultTableModel model = (DefaultTableModel) reminderTbl.getModel();        
        model.setRowCount(0); 
        for(WorkRequest request : account.getWorkQueue().getWorkRequestList()){ 
            if(((OrderReminderRequest)request).getMessage().equals("Please Processing")){
            Object[] row = new Object[5];
            row[0] = request;
            row[1] = ((OrderReminderRequest)request).getReminderCreated();
            row[2] = ((OrderReminderRequest)request).getMessage();
            row[3] = ((OrderReminderRequest)request).getStatus();
            model.addRow(row);
            
            
            
       } 
    }
               
        }
        else if(reminderCombo.getSelectedItem().equals("processed")){
            DefaultTableModel model = (DefaultTableModel) reminderTbl.getModel();
            model.setRowCount(0);
            for(WorkRequest request : account.getWorkQueue().getWorkRequestList()){ 
                if(((OrderReminderRequest)request).getMessage().equals("Processed")){
                Object[] row = new Object[5];
                row[0] = request;
                row[1] = ((OrderReminderRequest)request).getReminderCreated();
                row[2] = ((OrderReminderRequest)request).getMessage();
                row[3] = ((OrderReminderRequest)request).getStatus();
                model.addRow(row);
            
            
            
       } 
    }
        }
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        populateOrderTable();
         
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       
         populateDelete();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
         populateReminder();
    }//GEN-LAST:event_jButton6ActionPerformed
public void populateReminder(){
       DefaultTableModel model = (DefaultTableModel) reminderTbl.getModel();
       model.setRowCount(0);       
       for(WorkRequest request : account.getWorkQueue().getWorkRequestList()){                
            Object[] row = new Object[4];
            row[0] = (OrderReminderRequest)request;
            row[1] = ((OrderReminderRequest)request).getReminderCreated();
            row[2] = ((OrderReminderRequest)request).getMessage();
            row[3] = ((OrderReminderRequest)request).getStatus();
            model.addRow(row);   
    }
  }
  
   public void populateDelete(){
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.setRowCount(0);  
       for(WorkRequest request : account.getWorkQueue().getWorkRequestList()){            
            Object[] row = new Object[4];
            row[0] = (OrderReminderRequest)request;
            row[1] = ((OrderReminderRequest)request).getRequestCreated();
            row[2] = ((OrderReminderRequest)request).getDeleteMessage();
            row[3] = ((OrderReminderRequest)request).getDeleteStatus();
            model.addRow(row);  
    }
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel customer;
    private javax.swing.JComboBox<String> deleteCombo;
    private javax.swing.JButton detailBtn;
    private javax.swing.JTable itemTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> orderStatusCombo;
    private javax.swing.JTable orderTbl;
    private javax.swing.JButton productBtn;
    private javax.swing.JComboBox<String> reminderCombo;
    private javax.swing.JTable reminderTbl;
    private javax.swing.JButton requestBtn;
    // End of variables declaration//GEN-END:variables
}
