/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userinterface.dior.WarehouseRole;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Enterprise.BeautyEnterprise;
import Business.Enterprise.Enterprise;
import Business.Order.Item;
import Business.Order.Order;
import Business.Organization.Organization;
import Business.Product.Product;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author too
 */
public class AnalyzeOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AnalyzeOrder
     */
    JPanel userProcessContainer;
    UserAccount account;
    Organization organization;
    EcoSystem business;
    Enterprise enterprise;
    private BeautyEnterprise beauty;
    
    
    public AnalyzeOrderJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise,EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.business = business;
        this.enterprise = enterprise;
        this.beauty = (BeautyEnterprise)enterprise;
        populateorderComboBox();
        populateproductComboBox();
        populatecustomerOrderTable();
        populateproductTable();
    }

    public void populateorderComboBox(){
        orderComboBox.removeAllItems();
        orderComboBox.addItem("OrderNum");
        orderComboBox.addItem("TotalConsumption");
    }
    
    public void populateproductComboBox(){
        productComboBox.removeAllItems();
        productComboBox.addItem("Quantity");
        productComboBox.addItem("TotalRevenue");
    }
    
   public void populatecustomerOrderTable(){
        
        DefaultTableModel model = (DefaultTableModel)customerOrderTable.getModel();
        model.setRowCount(0);
        for(Customer customer : beauty.getCustomerDir().getCustomerList()){
            int countorder =0;
            double totalconsumption = 0;
            Object[] row = new Object[5];
            row[0] = customer;
            
            for(Order order : customer.getOrderDir().getOrderList()){
                countorder++;
                
                for(Item item : order.getOrderItemList()){
                    totalconsumption += item.getProduct().getSalesPrice()*item.getQuatity();
                }
            }
            row[1]=countorder;
            row[2]=totalconsumption;
            model.addRow(row);
        }   
    }

   public void populateproductTable(){
        
        DefaultTableModel model = (DefaultTableModel)productTable.getModel();
        model.setRowCount(0);
//        int soldQuantity = 0;
        for(Product product : beauty.getProductDir().getProductList()){
            int soldQuantity = 0;
            Object[] row = new Object[5];
            row[0]=product.getProductName();
            for(Customer customer : beauty.getCustomerDir().getCustomerList()){
                for(Order order : customer.getOrderDir().getOrderList()){
                    for(Item item : order.getOrderItemList()){
                        if(item.getProduct().getProductId() == product.getProductId()){
                        soldQuantity += item.getQuatity();
                        }     
                    }                    
                }
                
            }
            row[1]=soldQuantity;
            row[2]=product.getSalesPrice();
            row[3]=product.getPurchasingPrice();
            row[4]=soldQuantity*(product.getSalesPrice()-product.getPurchasingPrice());
            model.addRow(row);
        }   
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        analyseOrderBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        customerOrderTable = new javax.swing.JTable();
        analyseProductBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        orderComboBox = new javax.swing.JComboBox<>();
        productComboBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Order Analyze");

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "SoldQuantity", "Sale Price", "Purchasing Price", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(productTable);
        if (productTable.getColumnModel().getColumnCount() > 0) {
            productTable.getColumnModel().getColumn(0).setResizable(false);
            productTable.getColumnModel().getColumn(1).setResizable(false);
            productTable.getColumnModel().getColumn(2).setResizable(false);
            productTable.getColumnModel().getColumn(3).setResizable(false);
            productTable.getColumnModel().getColumn(4).setResizable(false);
        }

        analyseOrderBtn.setText("AnalyseOrder");
        analyseOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyseOrderBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Order List:");

        customerOrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Customer", "TotalOrder", "TotalComsuption"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(customerOrderTable);
        if (customerOrderTable.getColumnModel().getColumnCount() > 0) {
            customerOrderTable.getColumnModel().getColumn(0).setResizable(false);
            customerOrderTable.getColumnModel().getColumn(1).setResizable(false);
            customerOrderTable.getColumnModel().getColumn(2).setResizable(false);
        }

        analyseProductBtn.setText("AnalyseProduct");
        analyseProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyseProductBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Product List:");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        orderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        orderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderComboBoxActionPerformed(evt);
            }
        });

        productComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        productComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productComboBoxActionPerformed(evt);
            }
        });

        jButton1.setText("show chart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnBack)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1)
                                        .addGap(76, 76, 76)
                                        .addComponent(productComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(analyseProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(420, 420, 420))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(orderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(51, 51, 51)))
                                        .addComponent(analyseOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(67, 67, 67))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(314, 314, 314))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(87, 87, 87)))))))
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(analyseOrderBtn)
                                    .addComponent(orderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(208, 208, 208)
                                .addComponent(jLabel3)))
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(analyseProductBtn)
                            .addComponent(btnBack)
                            .addComponent(productComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(45, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(19, 19, 19))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void analyseOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyseOrderBtnActionPerformed

        if(orderComboBox.getSelectedItem() == "OrderNum"){
            populatecustomerOrderNumTable();    
        }
        if(orderComboBox.getSelectedItem() == "TotalConsumption"){
            populatecustomerConsumptionTable();
        }
        
    }//GEN-LAST:event_analyseOrderBtnActionPerformed

    private void orderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderComboBoxActionPerformed

    private void productComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productComboBoxActionPerformed

    private void analyseProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyseProductBtnActionPerformed
        // TODO add your handling code here:
 
        if(productComboBox.getSelectedItem() == "Quantity"){
            populateproductQuantityTable();    
        }
        if(productComboBox.getSelectedItem() == "TotalRevenue"){
            populateproductRevenueTable();
        }
    }//GEN-LAST:event_analyseProductBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
    //    dataset.setValue(WIDTH, WIDTH, PROPERTIES);
        dataset.setValue(80, "Marks", "Student1");
        dataset.setValue(50, "Marks", "Student2");
        dataset.setValue(75, "Marks", "Student3");
        dataset.setValue(95, "Marks", "Student4");
        for(Customer customer : beauty.getCustomerDir().getCustomerList()){
            int countorder =0;
            double totalconsumption = 0;
            for(Order order : customer.getOrderDir().getOrderList()){
                countorder++;
                for(Item item : order.getOrderItemList()){
                    totalconsumption += item.getProduct().getSalesPrice()*item.getQuatity();
                }
            }
            dataset.setValue(totalconsumption, "totalconsumption", customer.getFname()+""+customer.getLname());
              
        }
        
        
        
        
//      JFreeChart chart = ChartFactory.createBarChart("title of chartbar", "X-axis title", "Y-axis title", dataset);
        JFreeChart chart = ChartFactory.createBarChart("title of chartbar", "X-axis title", "Y-axis title", dataset, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot p = chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.black);
        ChartFrame frame = new ChartFrame("Bar Chart for Student", chart);
        frame.setVisible(true);
        frame.setSize(450,350);
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    public void populatecustomerConsumptionTable(){
        List<Customer> customers = new ArrayList();
        customers =beauty.getCustomerDir().getCustomerList();
        Collections.sort(customers, new Comparator<Customer>(){
        @Override
        public int compare(Customer c1, Customer c2){
            int countorder1 = 0;
            int totalconsumption1=0;
            int countorder2 = 0;
            int totalconsumption2=0;
            for(Order order : c1.getOrderDir().getOrderList()){
                countorder1++;
                for(Item item : order.getOrderItemList()){
                    totalconsumption1 += item.getProduct().getSalesPrice()*item.getQuatity();
                }
            }
            for(Order order : c2.getOrderDir().getOrderList()){
                countorder2++;
                for(Item item : order.getOrderItemList()){
                    totalconsumption2 += item.getProduct().getSalesPrice()*item.getQuatity();
                }
            } 
            if(totalconsumption1==totalconsumption2){
                if(countorder1 == countorder2){
                return 0;
                }
                return countorder1 > countorder2 ? -1:1;
            }
            return totalconsumption1 > totalconsumption2 ? -1: 1;
            }
        });
        
        DefaultTableModel model = (DefaultTableModel)customerOrderTable.getModel();
        model.setRowCount(0);           
        for(int i = 0; i< customers.size(); i++ ){
            Customer c = customers.get(i);
            int countorder =0;
            double totalconsumption = 0;
            Object[] row = new Object[5];
            row[0] = c;
            
            for(Order order : c.getOrderDir().getOrderList()){
                countorder++;
                
                for(Item item : order.getOrderItemList()){
                    totalconsumption += item.getProduct().getSalesPrice()*item.getQuatity();
                }
            }
            row[1]=countorder;
            row[2]=totalconsumption;
            model.addRow(row);
        }
        
        DefaultPieDataset pirDataset = new DefaultPieDataset();
        for(int i = 0; i< customers.size(); i++ ){
            Customer c = customers.get(i);
            int countorder =0;
            double totalconsumption = 0;
            for(Order order : c.getOrderDir().getOrderList()){
                countorder++;
                for(Item item : order.getOrderItemList()){
                    totalconsumption += item.getProduct().getSalesPrice()*item.getQuatity();
                }
            }
            pirDataset.setValue(c.getFname()+""+c.getLname(),totalconsumption);
              
        }
        
        
      JFreeChart chart = ChartFactory.createPieChart("Customer with Consumption", pirDataset,true,true,true);
      //  JFreeChart chart = ChartFactory.createBarChart("Customer Of order", "Customer", "Orders of Customer", pirDataset, PlotOrientation.VERTICAL, false, true, false);
        PiePlot p = (PiePlot)chart.getPlot();
      //  p.setForegroundAlpha(TOP_ALIGNMENT);
        

        ChartFrame frame = new ChartFrame("Customer with Consumption Pie Chart", chart);
        frame.setVisible(true);
        frame.setSize(450,500);
        
        
    }
    
    public void populatecustomerOrderNumTable(){
        List<Customer> customers = new ArrayList();
        for(Customer customer : beauty.getCustomerDir().getCustomerList()){
            customers.add(customer);
        }
        Collections.sort(customers, new Comparator<Customer>(){
        @Override
        public int compare(Customer c1, Customer c2){
            int countorder1 = 0;
            int totalconsumption1=0;
            int countorder2 = 0;
            int totalconsumption2=0;
            for(Order order : c1.getOrderDir().getOrderList()){
                countorder1++;
                for(Item item : order.getOrderItemList()){
                    totalconsumption1 += item.getProduct().getSalesPrice()*item.getQuatity();
                }
            }
            for(Order order : c2.getOrderDir().getOrderList()){
                countorder2++;
                for(Item item : order.getOrderItemList()){
                    totalconsumption2 += item.getProduct().getSalesPrice()*item.getQuatity();
                }
            } 
            if(countorder1 == countorder2){
                if(totalconsumption1==totalconsumption2){
                return 0;
                }
                return totalconsumption1>totalconsumption2 ? -1:1;
            }
            return countorder1 > countorder2 ? -1: 1;
            }
        });
        
        DefaultTableModel model = (DefaultTableModel)customerOrderTable.getModel();
        model.setRowCount(0);           
        for(int i = 0; i< customers.size(); i++ ){
            Customer c = customers.get(i);
            int countorder =0;
            double totalconsumption = 0;
            Object[] row = new Object[5];
            row[0] = c;
            for(Order order : c.getOrderDir().getOrderList()){
                countorder++;
                
                for(Item item : order.getOrderItemList()){
                    totalconsumption += item.getProduct().getSalesPrice()*item.getQuatity();
                }
            }
            row[1]=countorder;
            row[2]=totalconsumption;
            model.addRow(row);
        }
        
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for(int i = 0; i< customers.size(); i++ ){
            Customer c = customers.get(i);
            int countorder =0;
            double totalconsumption = 0;
            for(Order order : c.getOrderDir().getOrderList()){
                countorder++;
                for(Item item : order.getOrderItemList()){
                    totalconsumption += item.getProduct().getSalesPrice()*item.getQuatity();
                }
            }
            dataset.setValue(totalconsumption, "totalconsumption", c.getFname()+""+c.getLname());
              
        }
        
        
//      JFreeChart chart = ChartFactory.createBarChart("title of chartbar", "X-axis title", "Y-axis title", dataset);
        JFreeChart chart = ChartFactory.createBarChart("Customer Of order", "Customer", "Orders of Customer", dataset, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot p = chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.black);
        ChartFrame frame = new ChartFrame("Bar Chart for Student", chart);
        frame.setVisible(true);
        frame.setSize(450,350);
        
    }
    
    public void populateproductQuantityTable(){
        List<Product> products = new ArrayList();
        for(Product product : beauty.getProductDir().getProductList()){
            System.out.println();
            products.add(product);
        }
        Collections.sort(products, new Comparator<Product>(){
        @Override
        public int compare(Product p1, Product p2){
            int soldQuantity1 = 0;
            int soldQuantity2 = 0;
            int totalRevenue1 = 0;
            int totalRevenue2 = 0;
            
            for(Customer customer : beauty.getCustomerDir().getCustomerList()){
                for(Order order : customer.getOrderDir().getOrderList()){
                    for(Item item : order.getOrderItemList()){
                        if(item.getProduct().getProductId() == p1.getProductId()){
                        soldQuantity1 += item.getQuatity();
                        }
                        if(item.getProduct().getProductId() == p2.getProductId()){
                        soldQuantity2 += item.getQuatity();
                        }
                    }                    
                }
            }
            totalRevenue1 += soldQuantity1*(p1.getSalesPrice()-p1.getPurchasingPrice());
            totalRevenue2 += soldQuantity2*(p2.getSalesPrice()-p2.getPurchasingPrice());
              
            
            
            if(soldQuantity1 == soldQuantity2){
                if(totalRevenue1==totalRevenue2){
                return 0;
                }
                return totalRevenue1>totalRevenue2 ? -1:1;
            }
            return soldQuantity1 > soldQuantity2 ? -1: 1;
        }
        });
        
        DefaultTableModel model = (DefaultTableModel)productTable.getModel();
        model.setRowCount(0);           
        
        
        for(int i = 0; i< products.size(); i++ ){
            int soldQuantity = 0;
            Product product = products.get(i); 
            Object[] row = new Object[5];
            row[0]=product.getProductName();
            for(Customer customer : beauty.getCustomerDir().getCustomerList()){
                for(Order order : customer.getOrderDir().getOrderList()){
                    for(Item item : order.getOrderItemList()){
                        if(item.getProduct().getProductId() == product.getProductId()){
                        soldQuantity += item.getQuatity();
                        }     
                    }                    
                }
            }
            row[1]=soldQuantity;
            row[2]=product.getSalesPrice();
            row[3]=product.getPurchasingPrice();
            row[4]=soldQuantity*(product.getSalesPrice()-product.getPurchasingPrice());
            model.addRow(row);
        }
        
        
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        for(int i = 0; i< products.size(); i++ ){
            int soldQuantity = 0;
            Product product = products.get(i); 

            for(Customer customer : beauty.getCustomerDir().getCustomerList()){
                for(Order order : customer.getOrderDir().getOrderList()){
                    for(Item item : order.getOrderItemList()){
                        if(item.getProduct().getProductId() == product.getProductId()){
                        soldQuantity += item.getQuatity();
                        }     
                    }                    
                }
            }
            dataset.setValue(soldQuantity, "soldquantity", Integer.toString(product.getProductId()));
              
        }
        
        
//      JFreeChart chart = ChartFactory.createBarChart("title of chartbar", "X-axis title", "Y-axis title", dataset);
        JFreeChart chart = ChartFactory.createBarChart("SoldQuantity of Product", "Product", "Sold Quantity", dataset, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot p = chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.black);
        ChartFrame frame = new ChartFrame("Bar Chart for Student", chart);
        frame.setVisible(true);
        frame.setSize(450,350);
        
        
        
        
    }
    
    public void populateproductRevenueTable(){
        List<Product> products = new ArrayList();
        for(Product product : beauty.getProductDir().getProductList()){
            products.add(product);
        }
        Collections.sort(products, new Comparator<Product>(){
        @Override
        public int compare(Product p1, Product p2){
            int soldQuantity1 = 0;
            int soldQuantity2 = 0;
            int totalRevenue1 = 0;
            int totalRevenue2 = 0;
            
            for(Customer customer : beauty.getCustomerDir().getCustomerList()){
                for(Order order : customer.getOrderDir().getOrderList()){
                    for(Item item : order.getOrderItemList()){
                        if(item.getProduct().getProductId() == p1.getProductId()){
                        soldQuantity1 += item.getQuatity();
                        }
                        if(item.getProduct().getProductId() == p2.getProductId()){
                        soldQuantity2 += item.getQuatity();
                        }
                    }                    
                }
            }
            totalRevenue1 += soldQuantity1*(p1.getSalesPrice()-p1.getPurchasingPrice());
            totalRevenue2 += soldQuantity2*(p2.getSalesPrice()-p2.getPurchasingPrice());
              
            
            
            if(totalRevenue1 == totalRevenue2){
                if(soldQuantity1==soldQuantity2){
                return 0;
                }
                return soldQuantity1>soldQuantity2 ? -1:1;
            }
            return totalRevenue1 > totalRevenue2 ? -1: 1;
        }
        });
        
        DefaultTableModel model = (DefaultTableModel)productTable.getModel();
        model.setRowCount(0);           
        
        for(int i = 0; i< products.size(); i++ ){
            int soldQuantity = 0;
            Product product = products.get(i);  
            Object[] row = new Object[5];
            row[0]=product.getProductName();
            for(Customer customer : beauty.getCustomerDir().getCustomerList()){
                for(Order order : customer.getOrderDir().getOrderList()){
                    for(Item item : order.getOrderItemList()){
                        if(item.getProduct().getProductId() == product.getProductId()){
                        soldQuantity += item.getQuatity();
                        }     
                    }                    
                }
            }
                row[1]=soldQuantity;
                row[2]=product.getSalesPrice();
                row[3]=product.getPurchasingPrice();
                row[4]=soldQuantity*(product.getSalesPrice()-product.getPurchasingPrice());
                model.addRow(row);
            
        }
        
        
        DefaultPieDataset pirDataset = new DefaultPieDataset();
       for(int i = 0; i< products.size(); i++ ){
            int soldQuantity = 0;
            Product product = products.get(i);  
            for(Customer customer : beauty.getCustomerDir().getCustomerList()){
                for(Order order : customer.getOrderDir().getOrderList()){
                    for(Item item : order.getOrderItemList()){
                        if(item.getProduct().getProductId() == product.getProductId()){
                        soldQuantity += item.getQuatity();
                        }     
                    }                    
                }
            }
            
            pirDataset.setValue(product.getProductName(),soldQuantity*(product.getSalesPrice()-product.getPurchasingPrice()));
              
        }
        
      JFreeChart chart = ChartFactory.createPieChart("Product with Revenue", pirDataset,true,true,true);
      //  JFreeChart chart = ChartFactory.createBarChart("Customer Of order", "Customer", "Orders of Customer", pirDataset, PlotOrientation.VERTICAL, false, true, false);
        PiePlot p = (PiePlot)chart.getPlot();
       // p.setForegroundAlpha(TOP_ALIGNMENT);
        
        
        
       // p.setRangeGridlinePaint(Color.black);
        
        ChartFrame frame = new ChartFrame("Product with Revenue Pie Chart", chart);
        frame.setVisible(true);
        frame.setSize(450,500);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analyseOrderBtn;
    private javax.swing.JButton analyseProductBtn;
    private javax.swing.JButton btnBack;
    private javax.swing.JTable customerOrderTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> orderComboBox;
    private javax.swing.JComboBox<String> productComboBox;
    private javax.swing.JTable productTable;
    // End of variables declaration//GEN-END:variables
}
