/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userinterface.dior.WarehouseRole;

import Business.Customer.CustomerDirectory;
import Business.EcoSystem;
import Business.Enterprise.BeautyEnterprise;
import Business.Enterprise.Enterprise;
import Business.Order.OrderDirectory;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Userinterface.dior.WarehouseRole.OrderInfoJPanel;

/**
 *
 * @author too
 */
public class WarehouseWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form WarehouseWorkArea
     */
   JPanel userProcessContainer;
   UserAccount account;
   Organization organization;
   EcoSystem business;
   Enterprise enterprise;
   private BeautyEnterprise beauty;

    public WarehouseWorkArea(JPanel userProcessContainer, UserAccount account, Organization organization,Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.business = business;
        this.enterprise = enterprise;
        this.beauty = (BeautyEnterprise)enterprise;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        analyzeOrderBtn = new javax.swing.JButton();
        replennishmentBtn = new javax.swing.JButton();
        orderInfoBtn = new javax.swing.JButton();

        jLabel1.setText("Welcome to Warehouse Work Area");

        analyzeOrderBtn.setText("Analyze Order");
        analyzeOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyzeOrderBtnActionPerformed(evt);
            }
        });

        replennishmentBtn.setText("Replenishment/Update");
        replennishmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replennishmentBtnActionPerformed(evt);
            }
        });

        orderInfoBtn.setText("Order Information");
        orderInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderInfoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(247, 247, 247))
            .addGroup(layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orderInfoBtn)
                    .addComponent(replennishmentBtn)
                    .addComponent(analyzeOrderBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(orderInfoBtn)
                .addGap(18, 18, 18)
                .addComponent(analyzeOrderBtn)
                .addGap(18, 18, 18)
                .addComponent(replennishmentBtn)
                .addContainerGap(197, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void orderInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderInfoBtnActionPerformed
        // TODO add your handling code here:
        CustomerDirectory customerDir =  beauty.getCustomerDir();
        OrderInfoJPanel orderList = new OrderInfoJPanel(userProcessContainer,account,organization,business,enterprise,customerDir);
        userProcessContainer.add("OrderInfo", orderList);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_orderInfoBtnActionPerformed

    private void analyzeOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyzeOrderBtnActionPerformed
        // TODO add your handling code here:
        AnalyzeOrderJPanel analyzeorder = new AnalyzeOrderJPanel(userProcessContainer,account,organization,enterprise,business);
        userProcessContainer.add("OrderInfo", analyzeorder);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_analyzeOrderBtnActionPerformed

    private void replennishmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replennishmentBtnActionPerformed
        // TODO add your handling code here:
        ReplenishStockJPanel replenish = new ReplenishStockJPanel(userProcessContainer,account,organization,enterprise,business);
        userProcessContainer.add("OrderInfo", replenish);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_replennishmentBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analyzeOrderBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton orderInfoBtn;
    private javax.swing.JButton replennishmentBtn;
    // End of variables declaration//GEN-END:variables
}
